\version "2.24.3"
%% "Hourglass" -- for four voices, celesta, violins, cello, timpani and piano.
%%
%% A palindrome in four tempi.  The soprano's opening tune (bars 3-10, C minor,
%% crotchet = 48) returns at the end (bars 42-49) as its exact retrograde: the
%% same twenty notes in reverse order, with the same durations reversed, sung by
%% the tenor an octave down.  The words reverse with it -- the first phrase
%% "Fall, we shall, as sand" comes back as "sand, as shall we fall" -- and the
%% harmony underneath is re-read from C minor into E-flat major, the relative
%% major, so the identical pitches that were grief on the way down are consent
%% on the way back.
%%
%% Between the two halves the glass is turned.  Bars 11-30 are in 7/8 -- seven
%% quavers, because a seven-note scale then fills exactly one bar -- and the
%% tempo steps up every four bars while the mode darkens with it:
%%
%%     bars 11-14  transition       C aeolian        ♪ = 112 .. 160
%%     bars 15-18  hocket, solo     C aeolian        ♪ = 176
%%     bars 19-22  hocket, pairs    C dorian         ♪ = 200
%%     bars 23-26  hocket, pairs    C harmonic minor ♪ = 224
%%     bars 27-30  tutti            C phrygian dom.  ♪ = 248
%%
%% The hocket is a single seven-syllable line per bar passed between the four
%% voices one syllable at a time (soprano, alto, tenor, bass, soprano ...),
%% each voice taking the note in its own octave, so the tune is heard across
%% three octaves at once and no singer ever holds it for more than a quaver.
%% Seven syllables over four voices means the rotation only comes round every
%% four bars, which is why each step is four bars long.  Under it the violins
%% play a Shepard rise: two voices a bar apart, each climbing one octave per
%% bar, swelling on the way up and fading at the top, so the strings appear to
%% ascend for twenty bars without ever arriving.  The piano's ostinato groups
%% the bar 2+2+3 and the celesta ticks 3+2+2 against it.
%%
%% Bars 31-38 are the glass breaking: 4/4, crotchet = 132, parallel thirds in
%% octaves over tremolo, a held cluster, three stabs, and a general pause at
%% crotchet = 44 that the MIDI actually observes.  The celesta, silent through
%% all of that, is what is left ticking afterwards.
%%
%% Every voice part uses ties rather than extenders for held notes, so each
%% part's syllable count is exactly its number of untied notes and a miscount
%% is a LilyPond warning rather than a line that sings a word late.
%%
%% The hocket and the Shepard rise are generated by make_score.py in this
%% directory; everything else is written by hand.  hourglass.ly is the result
%% and is the file to compile.

#(set-global-staff-size 12)
\paper {
  #(set-paper-size "a4landscape")
  ragged-last-bottom = ##f
  system-system-spacing.basic-distance = #12
  top-margin = 8\mm
  bottom-margin = 8\mm
  left-margin = 12\mm
  right-margin = 10\mm
}

\header {
  title = "Hourglass"
  subtitle = "a palindrome in four tempi, for four voices, celesta, strings, timpani and piano"
  composer = "original composition"
  tagline = ##f
}

%% ---------------------------------------------------------------- the spine
%% Metre, key and every tempo in one place; each staff runs it alongside its
%% own notes.  Hidden tempo marks are the ones a conductor would take by feel:
%% the general pause and the staged ritardando at the end.
global = {
  \key c \minor
  \time 5/4 \tempo "I. Sand" 4 = 48
  s4*5*10 |
  \time 7/8 \tempo "II. Turning" 8 = 112 s8*7 |
  \tempo 8 = 128 s8*7 |
  \tempo 8 = 144 s8*7 |
  \tempo 8 = 160 s8*7 |
  \tempo 8 = 176 s8*7*4 |
  \tempo 8 = 200 s8*7*4 |
  \tempo 8 = 224 s8*7*4 |
  \tempo 8 = 248 s8*7*4 |
  \time 4/4 \tempo "III. Shatter" 4 = 132 s1*8 |
  \once \omit Score.MetronomeMark \tempo 4 = 44 s1 |
  \tempo 4 = 60 s1*2 |
  \time 5/4 \key ees \major \tempo "IV. Glass (Tempo I)" 4 = 48 s4*5*4 |
  \once \omit Score.MetronomeMark \tempo 4 = 44 s4*5*2 |
  \once \omit Score.MetronomeMark \tempo 4 = 40 s4*5*2 |
  \once \omit Score.MetronomeMark \tempo 4 = 36 s4*5 |
  \once \omit Score.MetronomeMark \tempo 4 = 32 s4*5 |
}

%% Two bars a system in 5/4, four in 7/8 and 4/4: the playhead in the video
%% then moves at much the same speed across the page whatever the metre.
breaks = {
  \repeat unfold 5 { s4*5*2 \break }
  \repeat unfold 5 { s8*7*4 \break }
  s1*4 \break s1*4 \break s1*3 \break
  \repeat unfold 4 { s4*5*2 \break } s4*5*2
}

%% ---- generated by make_score.py: the hocket, bars 15-30 ----

hocketS = {
    %% step 1: aeolian, ♪ = 176
    c''8\mp r4 r8 c''8 r4 |
    r8 aes'8 r4 r8 f'8 r8 |
    r4 c''8 r4 r8 f'8 |
    r4 r8 bes'8 r4 r8 |
    %% step 2: dorian, ♪ = 200
    c''8\mf r8 ees''8 r8 c''8 r8 c''8 |
    r8 a'8 r8 a'8 r8 f'8 r8 |
    ees''8 r8 c''8 r8 a'8 r8 f'8 |
    r8 g'8 r8 bes'8 r8 d''8 r8 |
    %% step 3: harmonic, ♪ = 224
    c''8\f r8 ees''8 r8 c''8 r8 c''8 |
    r8 aes'8 r8 aes'8 r8 f'8 r8 |
    ees''8 r8 c''8 r8 aes'8 r8 f'8 |
    r8 g'8 r8 b'8 r8 d''8 r8 |
    %% step 4: phrygdom, ♪ = 248
    c''8\ff des''8 e''8 des''8 c''8 bes'8 c''8 |
    g'8 aes'8 bes'8 aes'8 g'8 f'8 g'8 |
    e''8 des''8 c''8 bes'8 aes'8 g'8 f'8 |
    f'8\< g'8 aes'8 bes'8 c''8 des''8 e''8\! |
}

hocketSWords = \lyricmode {
    Turn count the the grain light, a Turn glass count grain, the and the "ev-" grain year light, "’ry" a of Turn glass count grain, the and the "ev-" grain year light, "’ry" a of Turn the glass and count the grain, turn the glass and name the hour, "ev-" "’ry" grain a year of light, "ev-" "’ry" year a grain of night.
}

hocketA = {
    %% step 1: aeolian, ♪ = 176
    r8 d''8\mp r4 r8 bes'8 r8 |
    r4 bes'8 r4 r8 g'8 |
    r4 r8 bes'8 r4 r8 |
    f'8 r4 r8 c''8 r4 |
    %% step 2: dorian, ♪ = 200
    r8 d''8\mf r8 d''8 r8 bes'8 r8 |
    g'8 r8 bes'8 r8 g'8 r8 g'8 |
    r8 d''8 r8 bes'8 r8 g'8 r8 |
    f'8 r8 a'8 r8 c''8 r8 ees''8 |
    %% step 3: harmonic, ♪ = 224
    c''8\f r8 ees''8 r8 c''8 r8 c''8 |
    r8 aes'8 r8 aes'8 r8 f'8 r8 |
    ees''8 r8 c''8 r8 aes'8 r8 f'8 |
    r8 g'8 r8 b'8 r8 d''8 r8 |
    %% step 4: phrygdom, ♪ = 248
    c''8\ff des''8 e''8 des''8 c''8 bes'8 c''8 |
    g'8 aes'8 bes'8 aes'8 g'8 f'8 g'8 |
    e''8 des''8 c''8 bes'8 aes'8 g'8 f'8 |
    f'8\< g'8 aes'8 bes'8 c''8 des''8 e''8\! |
}

hocketAWords = \lyricmode {
    the the glass hour, a "ev-" grain the and the turn glass name hour, "’ry" a of "ev-" year grain night. Turn glass count grain, the and the "ev-" grain year light, "’ry" a of Turn the glass and count the grain, turn the glass and name the hour, "ev-" "’ry" grain a year of light, "ev-" "’ry" year a grain of night.
}

hocketT = {
    %% step 1: aeolian, ♪ = 176
    r4 ees''8\mp r4 r8 c''8 |
    r4 r8 aes'8 r4 r8 |
    ees''8 r4 r8 aes'8 r4 |
    r8 g'8 r4 r8 d''8 r8 |
    %% step 2: dorian, ♪ = 200
    c''8\mf r8 ees''8 r8 c''8 r8 c''8 |
    r8 a'8 r8 a'8 r8 f'8 r8 |
    ees''8 r8 c''8 r8 a'8 r8 f'8 |
    r8 g'8 r8 bes'8 r8 d''8 r8 |
    %% step 3: harmonic, ♪ = 224
    r8 d''8\f r8 d''8 r8 b'8 r8 |
    g'8 r8 b'8 r8 g'8 r8 g'8 |
    r8 d''8 r8 b'8 r8 g'8 r8 |
    f'8 r8 aes'8 r8 c''8 r8 ees''8 |
    %% step 4: phrygdom, ♪ = 248
    c''8\ff des''8 e''8 des''8 c''8 bes'8 c''8 |
    g'8 aes'8 bes'8 aes'8 g'8 f'8 g'8 |
    e''8 des''8 c''8 bes'8 aes'8 g'8 f'8 |
    f'8\< g'8 aes'8 bes'8 c''8 des''8 e''8\! |
}

hocketTWords = \lyricmode {
    glass grain, and "ev-" year "’ry" of Turn glass count grain, the and the "ev-" grain year light, "’ry" a of the and the turn glass name hour, "’ry" a of "ev-" year grain night. Turn the glass and count the grain, turn the glass and name the hour, "ev-" "’ry" grain a year of light, "ev-" "’ry" year a grain of night.
}

hocketB = {
    %% step 1: aeolian, ♪ = 176
    r4 r8 d8\mp r4 r8 |
    g,8 r4 r8 g,8 r4 |
    r8 d8 r4 r8 g,8 r8 |
    r4 aes,8 r4 r8 ees8 |
    %% step 2: dorian, ♪ = 200
    r8 d8\mf r8 d8 r8 bes,8 r8 |
    g,8 r8 bes,8 r8 g,8 r8 g,8 |
    r8 d8 r8 bes,8 r8 g,8 r8 |
    f,8 r8 a,8 r8 c8 r8 ees8 |
    %% step 3: harmonic, ♪ = 224
    r8 d8\f r8 d8 r8 b,8 r8 |
    g,8 r8 b,8 r8 g,8 r8 g,8 |
    r8 d8 r8 b,8 r8 g,8 r8 |
    f,8 r8 aes,8 r8 c8 r8 ees8 |
    %% step 4: phrygdom, ♪ = 248
    c8\ff des8 e8 des8 c8 bes,8 c8 |
    g,8 aes,8 bes,8 aes,8 g,8 f,8 g,8 |
    e8 des8 c8 bes,8 aes,8 g,8 f,8 |
    f,8\< g,8 aes,8 bes,8 c8 des8 e8\! |
}

hocketBWords = \lyricmode {
    and turn name "’ry" of year night. the and the turn glass name hour, "’ry" a of "ev-" year grain night. the and the turn glass name hour, "’ry" a of "ev-" year grain night. Turn the glass and count the grain, turn the glass and name the hour, "ev-" "’ry" grain a year of light, "ev-" "’ry" year a grain of night.
}

hocketPiano = {
    %% step 3: harmonic, ♪ = 224
    <c' c''>8\f <d' d''>8 <ees' ees''>8 <d' d''>8 <c' c''>8 <b b'>8 <c' c''>8 |
    <g g'>8 <aes aes'>8 <b b'>8 <aes aes'>8 <g g'>8 <f f'>8 <g g'>8 |
    <ees' ees''>8 <d' d''>8 <c' c''>8 <b b'>8 <aes aes'>8 <g g'>8 <f f'>8 |
    <f f'>8 <g g'>8 <aes aes'>8 <b b'>8 <c' c''>8 <d' d''>8 <ees' ees''>8 |
    %% step 4: phrygdom, ♪ = 248
    <c' c''>8\ff <des' des''>8 <e' e''>8 <des' des''>8 <c' c''>8 <bes bes'>8 <c' c''>8 |
    <g g'>8 <aes aes'>8 <bes bes'>8 <aes aes'>8 <g g'>8 <f f'>8 <g g'>8 |
    <e' e''>8 <des' des''>8 <c' c''>8 <bes bes'>8 <aes aes'>8 <g g'>8 <f f'>8 |
    <f f'>8\< <g g'>8 <aes aes'>8 <bes bes'>8 <c' c''>8 <des' des''>8 <e' e''>8\! |
}

%% ---- generated by make_score.py: the Shepard rise, bars 11-30 ----

shepardOne = {
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' a' bes' |
    c''8\mf\> d'' ees'' f'' g'' a'' bes'' |
    c'8\pp\< d' ees' f' g' a' bes' |
    c''8\mf\> d'' ees'' f'' g'' a'' bes'' |
    c'8\pp\< d' ees' f' g' aes' b' |
    c''8\mf\> d'' ees'' f'' g'' aes'' b'' |
    c'8\pp\< d' ees' f' g' aes' b' |
    c''8\mf\> d'' ees'' f'' g'' aes'' b'' |
    c'8\pp\< des' e' f' g' aes' bes' |
    c''8\mf\> des'' e'' f'' g'' aes'' bes'' |
    c'8\pp\< des' e' f' g' aes' bes' |
    c''8\mf\> des'' e'' f'' g'' aes'' bes''\! |
}

shepardTwo = {
    s8*7 |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' bes'' |
    c'8\pp\< d' ees' f' g' aes' bes' |
    c''8\mf\> d'' ees'' f'' g'' a'' bes'' |
    c'8\pp\< d' ees' f' g' a' bes' |
    c''8\mf\> d'' ees'' f'' g'' a'' bes'' |
    c'8\pp\< d' ees' f' g' a' bes' |
    c''8\mf\> d'' ees'' f'' g'' aes'' b'' |
    c'8\pp\< d' ees' f' g' aes' b' |
    c''8\mf\> d'' ees'' f'' g'' aes'' b'' |
    c'8\pp\< d' ees' f' g' aes' b' |
    c''8\mf\> des'' e'' f'' g'' aes'' bes'' |
    c'8\pp\< des' e' f' g' aes' bes' |
    c''8\mf\> des'' e'' f'' g'' aes'' bes'' |
    c'8\pp\< des' e' f' g' aes' bes'\! |
}


%% ------------------------------------------------------------------ soprano
sopranoMusic = {
  \clef treble
  %% I. the tune.  Twenty notes; the tenor sings them backwards at bar 42.
  R4*5*2 |
  g'2.\mp ees'2 | f'4 g'4 aes'2. | g'2 f'4 ees'2 | d'2. c'2 |
  bes'2.\mf aes'4 g'4 | f'4 ees'2. r4 | g'2\< aes'4 bes'2 | g'4\f c''2~\> c''2\! |
  %% II.
  R8*7*4 |
  \hocketS
  %% III.
  c''1\fff | c''8 c''8 bes'8 aes'8 g'4 ees''4 | d''4 ees''8 d''8 c''4 bes'4 |
  c''4 d''8 c''8 aes'4 g'4 |
  aes'1\ff\<~ | aes'1~ | aes'2\fff r8 aes'8 r8 aes'8 | aes'4 r4 r2 |
  R1\fermata^\markup { \bold "G.P." } | R1*2 |
  %% IV.  a vowel held over the tenor, then the last five words with him.
  ees''1\pp~ ees''4 | d''1~ d''4 | c''1~ c''4 | bes'1~ bes'4 |
  c''1\<~ c''4^\markup { \italic "rit. poco a poco" } | ees''1\mp~ ees''4 |
  c''2.\mp bes'4 aes'4 | g'2 bes'2.~\> |
  bes'1~ bes'4~ | bes'1~ bes'4\! \bar "|."
}

sopranoWords = \lyricmode {
  Fall, we shall, as sand, through the nar -- row hour,
  ev -- "’ry" grain a name, ev -- "’ry" name a light.
  \hocketSWords
  Break! let it break, let it spill, ev -- "’ry" grain a year,
  ev -- "’ry" year a grain, fall! fall! fall! fall!
  Ah Ah Ah Ah Ah Ah sand, as shall we fall.
}

%% --------------------------------------------------------------------- alto
altoMusic = {
  \clef treble
  R4*5*2 |
  ees'1\pp~ ees'4 | c'1~ c'4 | ees'1~ ees'4 | d'2. ees'2 |
  f'1\<~ f'4 | c'1\mp~ c'4 | ees'1~ ees'4 | g'1\>~ g'4\! |
  R8*7*4 |
  \hocketA
  bes'1\fff | aes'8 aes'8 g'8 f'8 ees'4 c''4 | bes'4 c''8 bes'8 aes'4 g'4 |
  aes'4 bes'8 aes'8 f'4 ees'4 |
  g'1\ff\<~ | g'1~ | g'2\fff r8 g'8 r8 g'8 | g'4 r4 r2 |
  R1 | R1*2 |
  c''1\pp~ c''4 | bes'1~ bes'4 | aes'1~ aes'4 | g'1~ g'4 |
  aes'1\<~ aes'4 | c''1\mp~ c''4 |
  ees'2.\mp ees'4 d'4 | ees'2 g'2.~\> |
  g'1~ g'4~ | g'1~ g'4\! \bar "|."
}

altoWords = \lyricmode {
  Mm Mm Mm Mm Mm Mm Mm Mm Mm
  \hocketAWords
  Break! let it break, let it spill, ev -- "’ry" grain a year,
  ev -- "’ry" year a grain, fall! fall! fall! fall!
  Ah Ah Ah Ah Ah Ah sand, as shall we fall.
}

%% -------------------------------------------------------------------- tenor
%% Written where a tenor staff is read -- the treble_8 clef means this part
%% sounds an octave below the printed pitch, and \transpose is what makes
%% LilyPond's MIDI agree with the clef. Without it the tenor sounded in unison
%% with the soprano: same range, same pitch on 58 of their 91 shared onsets,
%% which is three parts fused into one audible line instead of three.
tenorMusic = \transpose c' c {
  \clef "treble_8"
  R4*5*2 |
  c''1\pp~ c''4 | aes'1~ aes'4 | c''1~ c''4 | bes'2. aes'2 |
  d''1\<~ d''4 | aes'1\mp~ aes'4 | c''1~ c''4 | ees''1\>~ ees''4\! |
  R8*7*4 |
  \hocketT
  aes'1\fff | c''8 c''8 bes'8 aes'8 g'4 ees''4 | d''4 ees''8 d''8 c''4 bes'4 |
  c''4 d''8 c''8 aes'4 g'4 |
  f'1\ff\<~ | f'1~ | f'2\fff r8 f'8 r8 f'8 | f'4 r4 r2 |
  R1 | R1*2 |
  %% IV. the retrograde: bars 3-10 read from the last note to the first.
  c''1\p g'4 | bes'2 aes'4 g'2 | r4 ees'2. f'4 | g'4 aes'4 bes'2. |
  c'2 d'2. | ees'2\< f'4 g'2 | aes'2.\mp g'4 f'4 | ees'2 g'2.~\> |
  g'1~ g'4~ | g'1~ g'4\! \bar "|."
}

tenorWords = \lyricmode {
  Mm Mm Mm Mm Mm Mm Mm Mm Mm
  \hocketTWords
  Break! let it break, let it spill, ev -- "’ry" grain a year,
  ev -- "’ry" year a grain, fall! fall! fall! fall!
  Rise now from the glass, the hour turns a -- gain,
  and we who were held: sand, as shall we fall.
}

%% --------------------------------------------------------------------- bass
bassMusic = {
  \clef bass
  R4*5*2 |
  c1\pp~ c4 | f2. aes2 | g1~ g4 | g2. aes2 |
  bes1\<~ bes4 | f1\mp~ f4 | c1~ c4 | c1\>~ c4\! |
  R8*7*4 |
  \hocketB
  f1\fff | aes8 aes8 g8 f8 ees4 c'4 | bes4 c'8 bes8 aes4 g4 |
  aes4 bes8 aes8 f4 ees4 |
  ees1\ff\<~ | ees1~ | ees2\fff r8 ees8 r8 ees8 | ees4 r4 r2 |
  R1 | R1*2 |
  aes,1\pp~ aes,4 | bes,2. ees2 | aes,1~ aes,4 | ees1~ ees4 |
  bes,1\<~ bes,4 | c1\mp~ c4 |
  aes,2.\mp bes,4 bes,4 | ees2 ees2.~\> |
  ees1~ ees4~ | ees1~ ees4\! \bar "|."
}

bassWords = \lyricmode {
  Mm Mm Mm Mm Mm Mm Mm Mm Mm Mm
  \hocketBWords
  Break! let it break, let it spill, ev -- "’ry" grain a year,
  ev -- "’ry" year a grain, fall! fall! fall! fall!
  Mm Mm Mm Mm Mm Mm Mm sand, as shall we fall.
}

%% ------------------------------------------------------------------ celesta
%% The bells: c g ees d g c.  In part IV they come back reversed too.
celestaMusic = {
  \clef treble
  c''2\p g''4 ees'''2 | d'''2 g''4 c''2 |
  c''2\pp g''4 ees'''2 | d'''2 g''4 c''2 | R4*5*2 |
  c''2\p g''4 ees'''2 | d'''2 g''4 c''2 | R4*5 | r2 r4 c'''2\pp |
  %% II. the tick, 3+2+2 against the piano's 2+2+3
  c'''8\pp r4 g''8 r8 ees'''8 r8 | c'''8 r4 g''8 r8 ees'''8 r8 |
  c'''8\p r4 g''8 r8 ees'''8 r8 | c'''8 r4 g''8 r8 ees'''8 r8 |
  \repeat unfold 4 { c'''8\mp r4 g''8 r8 ees'''8 r8 | }
  \repeat unfold 4 { c'''8\mf r4 g''8 r8 ees'''8 r8 | }
  \repeat unfold 4 { c'''8\f r4 g''8 r8 ees'''8 r8 | }
  \repeat unfold 3 { c'''8\ff g''8 c'''8 g''8 c'''8 g''8 g''8 | }
  c'''8\< des'''8 e'''8 f'''8 g'''8 aes'''8 bes'''8\! |
  %% III. silent
  R1*8 | R1\fermata |
  c'''2\pp r2 | r2 g''2 |
  %% IV. the bells reversed: c g d ees g c
  c''2\pp g''4 d'''2 | ees'''2 g''4 c''2 | R4*5*2 |
  c''2\pp g''4 d'''2 | ees'''2 g''4 c''2 | R4*5*2 |
  c''2\pp g''4 d'''2 | ees'''2 g''4 r4 ees''''4\ppp \bar "|."
}

%% ------------------------------------------------------------------ violins
violinMusic = {
  \clef treble
  R4*5*2 |
  g'1\pp~ g'4 | aes'1~ aes'4 | g'1~ g'4 | d''1~ d''4 |
  f''1\<~ f''4 | ees''1\mp~ ees''4 | d''1~ d''4 | ees''1\>~ ees''4\! |
  %% II. the Shepard rise
  << { \voiceOne \shepardOne } \\ { \voiceTwo \shepardTwo } >>
  %% III.
  \repeat unfold 4 { \repeat tremolo 4 { <g'' c'''>32\fff <g'' c'''>32 } } |
  c''16 c'' c'' c'' c'' c'' c'' c'' bes' bes' bes' bes' aes' aes' aes' aes' |
  d''16 d'' d'' d'' ees'' ees'' ees'' ees'' d'' d'' d'' d'' c'' c'' c'' c'' |
  c''16 c'' c'' c'' d'' d'' d'' d'' c'' c'' c'' c'' aes' aes' aes' aes' |
  \repeat tremolo 4 { <aes' ees''>32\ff\< <aes' ees''>32 }
  \repeat unfold 3 { \repeat tremolo 4 { <aes' ees''>32 <aes' ees''>32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { <aes' ees''>32 <aes' ees''>32 } } |
  \repeat unfold 2 { \repeat tremolo 4 { <aes' ees''>32 <aes' ees''>32 } }
  r8 <aes' ees''>8\fff r8 <aes' ees''>8 |
  <aes' ees''>4 r4 r2 |
  R1 | R1*2 |
  %% IV.
  aes'1\pp~ aes'4 | g'1~ g'4 | aes'1~ aes'4 | g'1~ g'4 |
  f'1\<~ f'4 | g'1\p~ g'4 |
  ees''2. d''4 d''4 | ees''2 f''2.~\> |
  f''1~ f''4~ | f''1~ f''4\! \bar "|."
}

%% -------------------------------------------------------------------- cello
celloMusic = {
  \clef bass
  c,1\pp~ c,4 | c,1~ c,4 |
  c,1~ c,4 | f,2. aes,2 | c,1~ c,4 | g,2. aes,2 |
  bes,1\<~ bes,4 | f,1\mp~ f,4 | c,2. aes,2 | c,1\>~ c,4\! |
  %% II. 3+2+2 with the celesta
  c,4.\pp\< c,4 c,4 | c,4. c,4 c,4 | c,4. c,4 c,4 | c,4. c,4 c,4\mp |
  \repeat unfold 4 { c,4.\mp c,4 c,4 | }
  \repeat unfold 4 { c,4.\mf c,4 c,4 | }
  \repeat unfold 4 { c,4.\f c,4 g,4 | }
  \repeat unfold 3 { c,8\ff c,8 c,8 c,8 c,8 c,8 c,8 | }
  c,8\< c,8 c,8 c,8 c,8 c,8 c,8\! |
  %% III.
  \repeat unfold 4 { \repeat tremolo 4 { c,32\fff c,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c,32 } } |
  \repeat tremolo 4 { aes,32\ff\< aes,32 }
  \repeat unfold 3 { \repeat tremolo 4 { aes,32 aes,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { aes,32 aes,32 } } |
  \repeat unfold 2 { \repeat tremolo 4 { aes,32 aes,32 } }
  r8 aes,8\fff r8 aes,8 |
  aes,4 r4 r2 |
  R1 | R1 | ees,1\ppp\< |
  %% IV.
  aes,1\p~ aes,4 | bes,2. ees,2 | aes,1~ aes,4 | ees,1~ ees,4 |
  bes,1\<~ bes,4 | c,1\mp~ c,4 |
  aes,2. bes,2 | ees,1\>~ ees,4~ |
  ees,1~ ees,4~ | ees,1~ ees,4\! \bar "|."
}

%% ------------------------------------------------------------------ timpani
timpaniMusic = {
  \clef bass
  R4*5*10 |
  %% II. 2+2+3 with the piano
  c,4\pp\< c,4 c,4. | c,4 c,4 c,4. | c,4 c,4 c,4. | c,4 c,4 c,4.\mp |
  \repeat unfold 4 { c,4\mp c,4 c,4. | }
  \repeat unfold 4 { c,4\mf c,4 c,4. | }
  \repeat unfold 4 { c,4\f c,4 c,8 c,8 c,8 | }
  \repeat unfold 3 { c,8\ff c,8 c,8 c,8 c,8 c,8 c,8 | }
  \repeat tremolo 4 { c,32\< c,32 } \repeat tremolo 4 { c,32 c,32 }
  \repeat tremolo 6 { c,32 c,32\! } |
  %% III.
  \repeat unfold 4 { \repeat tremolo 4 { c,32\fff c,32 } } |
  c,8 c,8 c,4 c,8 c,8 c,4 | c,8 c,8 c,4 c,8 c,8 c,4 | c,8 c,8 c,4 c,8 c,8 c,4 |
  \repeat tremolo 4 { aes,32\ff\< aes,32 }
  \repeat unfold 3 { \repeat tremolo 4 { aes,32 aes,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { aes,32 aes,32 } } |
  \repeat unfold 2 { \repeat tremolo 4 { aes,32 aes,32 } }
  r8 aes,8\fff r8 aes,8 |
  aes,4 r4 r2 |
  R1 | R1*2 |
  R4*5*8 |
  R4*5 |
  \repeat tremolo 4 { ees,32\pp\> ees,32 }
  \repeat unfold 3 { \repeat tremolo 4 { ees,32 ees,32 } }
  \repeat tremolo 4 { ees,32\! ees,32 } \bar "|."
}

%% -------------------------------------------------------------------- piano
pianoUpper = {
  \clef treble
  R4*5*6 |
  <d' f' bes'>1\pp~ <d' f' bes'>4 | <c' f' aes'>1~ <c' f' aes'>4 |
  <c' ees' g'>1~ <c' ees' g'>4 | <c' ees' g'>1\>~ <c' ees' g'>4\! |
  %% II. 2+2+3 chords, then the hocket line doubled in octaves
  R8*7*4 |
  \repeat unfold 4 { <ees' g'>4\mp <ees' g'>4 <d' g'>4. | }
  \repeat unfold 4 { <ees' g'>4\mf <ees' g'>4 <d' g'>4. | }
  \hocketPiano
  %% III.
  <f' aes' bes' c'' ees''>1\fff |
  <aes' c''>8 <aes' c''>8 <g' bes'>8 <f' aes'>8 <ees' g'>4 <c'' ees''>4 |
  <bes' d''>4 <c'' ees''>8 <bes' d''>8 <aes' c''>4 <g' bes'>4 |
  <aes' c''>4 <bes' d''>8 <aes' c''>8 <f' aes'>4 <ees' g'>4 |
  \repeat tremolo 4 { <ees' g' aes'>32\ff\< <f' aes' ees''>32 }
  \repeat unfold 3 { \repeat tremolo 4 { <ees' g' aes'>32 <f' aes' ees''>32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { <ees' g' aes'>32 <f' aes' ees''>32 } } |
  \repeat unfold 2 { \repeat tremolo 4 { <ees' g' aes'>32 <f' aes' ees''>32 } }
  r8 <ees' f' g' aes'>8\fff r8 <ees' f' g' aes'>8 |
  <ees' f' g' aes'>4 r4 r2 |
  R1\fermata | R1*2 |
  %% IV. E-flat major, one chord a bar, rising and falling
  aes8\pp c' ees' g' aes' g' ees' c' aes c' |
  bes8 ees' g' bes' ees'' bes' g' ees' bes ees' |
  aes8 c' ees' aes' c'' aes' ees' c' aes c' |
  ees'8 g' bes' ees'' g'' ees'' bes' g' ees' g' |
  bes8\< d' f' aes' d'' aes' f' d' bes d' |
  c'8\p ees' g' bes' ees'' bes' g' ees' c' ees' |
  aes8 c' ees' aes' c'' aes' bes d' f' bes' |
  ees'8 g' bes' ees'' g'' ees'' bes' g' ees' g' |
  <g' bes' ees''>1\pp\>~ <g' bes' ees''>4~ | <g' bes' ees''>1~ <g' bes' ees''>4\! \bar "|."
}

pianoLower = {
  \clef bass
  <c,, c,>1\pp~ <c,, c,>4 | <c,, c,>1~ <c,, c,>4 |
  <c,, c,>1~ <c,, c,>4 | <f,, f,>2. <aes,, aes,>2 | <c,, c,>1~ <c,, c,>4 |
  <g,, g,>2. <aes,, aes,>2 |
  <bes,, bes,>1\<~ <bes,, bes,>4 | <f,, f,>1\mp~ <f,, f,>4 |
  <c,, c,>2. <aes,, aes,>2 | <c,, c,>1\>~ <c,, c,>4\! |
  %% II. the ostinato, 2+2+3
  c,8\pp\< g,8 c8 g,8 c,8 g,8 c8 | c,8 g,8 c8 g,8 c,8 g,8 c8 |
  c,8 g,8 c8 g,8 c,8 g,8 c8 | c,8 g,8 c8 g,8 c,8 g,8 c8\mp |
  \repeat unfold 4 { c,8\mp g,8 c8 g,8 c,8 g,8 c8 | }
  \repeat unfold 4 { c,8\mf g,8 c8 g,8 c,8 g,8 c8 | }
  \repeat unfold 4 { c,8\f g,8 c8 g,8 c,8 g,8 c8 | }
  \repeat unfold 3 { <c, c>8\ff <g, g>8 <c, c>8 <g, g>8 <c, c>8 <g, g>8 <c, c>8 | }
  <c, c>8\< <g, g>8 <c, c>8 <g, g>8 <c, c>8 <g, g>8 <c, c>8\! |
  %% III.
  \repeat unfold 4 { \repeat tremolo 4 { c,32\fff c32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { c,32 c32 } } |
  \repeat tremolo 4 { aes,,32\ff\< aes,32 }
  \repeat unfold 3 { \repeat tremolo 4 { aes,,32 aes,32 } } |
  \repeat unfold 4 { \repeat tremolo 4 { aes,,32 aes,32 } } |
  \repeat unfold 2 { \repeat tremolo 4 { aes,,32 aes,32 } }
  r8 <aes,, aes,>8\fff r8 <aes,, aes,>8 |
  <aes,, aes,>4 r4 r2 |
  R1 | R1*2 |
  %% IV.
  <aes,, aes,>1\pp~ q4 | <bes,, bes,>2. <ees, ees>2 | <aes,, aes,>1~ q4 |
  <ees, ees>1~ q4 | <bes,, bes,>1\<~ q4 | <c, c>1\p~ q4 |
  <aes,, aes,>2. <bes,, bes,>2 | <ees, ees>1\>~ q4~ |
  q1~ q4~ | q1~ q4\! \bar "|."
}

%% -------------------------------------------------------------------- score
\score {
  <<
    \new Devnull { \breaks }
    \new ChoirStaff <<
      \new Staff = "soprano" \with {
        instrumentName = "Soprano" shortInstrumentName = "S."
        midiInstrument = "choir aahs"
      } << \global \new Voice = "soprano" \sopranoMusic >>
      \new Lyrics \lyricsto "soprano" \sopranoWords
      \new Staff = "alto" \with {
        instrumentName = "Alto" shortInstrumentName = "A."
        midiInstrument = "voice oohs"
      } << \global \new Voice = "alto" \altoMusic >>
      \new Lyrics \lyricsto "alto" \altoWords
      \new Staff = "tenor" \with {
        instrumentName = "Tenor" shortInstrumentName = "T."
        midiInstrument = "choir aahs"
      } << \global \new Voice = "tenor" \tenorMusic >>
      \new Lyrics \lyricsto "tenor" \tenorWords
      \new Staff = "bass" \with {
        instrumentName = "Bass" shortInstrumentName = "B."
        midiInstrument = "voice oohs"
      } << \global \new Voice = "bass" \bassMusic >>
      \new Lyrics \lyricsto "bass" \bassWords
    >>
    \new Staff = "celesta" \with {
      instrumentName = "Celesta" shortInstrumentName = "Cel."
      midiInstrument = "celesta"
    } << \global \celestaMusic >>
    \new StaffGroup <<
      \new Staff = "violins" \with {
        instrumentName = "Violins" shortInstrumentName = "Vln."
        midiInstrument = "string ensemble 1"
      } << \global \violinMusic >>
      \new Staff = "cello" \with {
        instrumentName = "Cello" shortInstrumentName = "Vc."
        midiInstrument = "cello"
      } << \global \celloMusic >>
    >>
    \new Staff = "timpani" \with {
      instrumentName = "Timpani" shortInstrumentName = "Timp."
      midiInstrument = "timpani"
    } << \global \timpaniMusic >>
    \new PianoStaff \with { instrumentName = "Piano" shortInstrumentName = "Pno." } <<
      \new Staff = "piano upper" \with { midiInstrument = "acoustic grand" }
        << \global \pianoUpper >>
      \new Staff = "piano lower" \with { midiInstrument = "acoustic grand" }
        << \global \pianoLower >>
    >>
  >>
  \layout { }
  \midi { }
}
